# Generated by Django 3.2.3 on 2021-09-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_image_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('COLOR_DISTANCE', 'COLORIZED'), ('GRADENT_VARIATION', 'Gradent variation'), ('GRADIENT_VARIATION_NORM', 'Gradent variation'), ('SUM_GRADIENTE_VARIATION', 'Sum gradient variation')], max_length=50, null=1),
        ),
    ]
