# Generated by Django 3.2.3 on 2021-10-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_image_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='action',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
